---
pub_dataset_path: ground_truth
priv_dataset_path: state-2-data
#priv_dataset_path: ground_truth
parameter_spec: ./data/parameters.json
numerical_binning:
  "AGE":
    - 20
    - 105
    - 5
  "INCTOT":
    - 0
    - 105_000
    - 5_000
  "INCWAGE":
    - 0
    - 105_000
    - 5_000
  "INCWELFR":
    - 0
    - 105_000
    - 5_000
  "INCINVST":
    - 0
    - 105_000
    - 5_000
  "INCEARN":
    - 0
    - 105_000
    - 5_000
  "POVERTY":
    - 0
    - 520
    - 20
  "HHWT":
    - 0
    - 520
    - 20
  "PERWT":
    - 0
    - 520
    - 20
  "DEPARTS":
    - 0
    - 15
    - 30
    - 45
  "ARRIVES":
    - 0
    - 15
    - 30
    - 45
grouping_attributes: {}
determined_attributes: {}
