---
# pub sampling
#priv_PUMA_YEAR:
#  total_eps: 0.25
#  attributes:
#    - 'PUMA'
#    - 'YEAR'

#### 1-way
#priv_PUMA_YEAR:
#  total_eps: 0.12
#  attributes:
#    - 'PUMA'
#    - 'YEAR'
#priv_all_one_way:
#  total_eps: 0.13

#### 2-way
priv_PUMA_YEAR:
  total_eps: 0.12
  attributes:
    - 'PUMA'
    - 'YEAR'
priv_all_two_way:
  total_eps: 0.13